apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  labels:
    app: nlp-api

spec:
  containers:
    - name: nlp-api-ctr
      image: rizcodes/riz-docker-repo:latest
      ports:
        - containerPort: 8000
