apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy
  labels:
    app: nlp-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nlp-api
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0 # No pods should be unavailable
      maxSurge: 1 # Update one pod at a time and there can be 3 (replicas + maxSurge) pods during rolling update.
      # After 15 secs (minReadySeconds), one pod will be terminated keeping count to 2 (replicas).
      # Same continues until all replica pods are upgraded.
  template:
    metadata:
      labels:
        app: nlp-api
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: api-pod
          image: rizcodes/riz-docker-repo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
